name: Build CarTool Static Library

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 26.1

    - name: Build Static Library
      run: |
        chmod +x build_static_cartool.sh
        ./build_ios.sh

    - name: Upload Static Library Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CarTool-Static
        path: |
          build/libCarTool.a
          build/include
